In [1]:
#import evidently

In [2]:
# from evidently.dashboard import Dashboard
# from evidently.tabs import DataDriftTab, CatTargetDriftTab
# from evidently.profile_sections import DataDriftProfileSection

C:\Users\ZagkouI\AppData\Roaming\Python\Python36\site-packages\evidently\analyzers\__init__.py:3: UserWarning: analyzers are deprecated, use metrics instead
  warnings.warn("analyzers are deprecated, use metrics instead")
C:\Users\ZagkouI\AppData\Roaming\Python\Python36\site-packages\evidently\dashboard\__init__.py:8: UserWarning:

dashboards are deprecated, use metrics instead

C:\Users\ZagkouI\AppData\Roaming\Python\Python36\site-packages\evidently\tabs\__init__.py:9: UserWarning:

'import evidently.tabs' is deprecated, use 'import evidently.dashboard.tabs'

C:\Users\ZagkouI\AppData\Roaming\Python\Python36\site-packages\evidently\model_profile\__init__.py:8: UserWarning:

model profiles are deprecated, use metrics instead

C:\Users\ZagkouI\AppData\Roaming\Python\Python36\site-packages\evidently\profile_sections\__init__.py:9: UserWarning:

'import evidently.profile_sections' is deprecated, use 'import evidently.model_profile.sections'



In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os
import re

In [8]:
#from imblearn.pipeline import Pipeline
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
#from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
#from xgboost import XGBClassifier
import lightgbm as lgb
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import classification_report
#from sklearn.model_selection import RandomizedSearchCV
#from sklearn.model_selection import GridSearchCV
#from sklearn.externals import joblib

In [23]:
import shap

ModuleNotFoundError: No module named 'numba.core'

In [24]:
pd.set_option('display.max_columns', 550)
pd.set_option('display.max_rows', 550)
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# LOAD TRAINING SET

In [10]:
previous_dataset = pd.read_csv('C:/Users/zagkoui/OneDrive - Vodafone Group/Documents/HIGHER_BUNDLES/final_data/train/final_customer_db.csv', index_col=0)

In [11]:
previous_dataset.head()

MSISDN  M1_TTL_OUT_CALLS  M1_TTL_OUT_MINUTES  M1_TTL_OUT_REVENUE  \
0  6948724826               119           61.100000              1.9192   
1  6949281531               130          409.833333              0.9944   
2  6949625761                14           10.316667              0.0000   
3  6949975996                 4            0.283333              0.0000   
4  6951507651                28           14.750000              0.0000   

   M1_V_CALLS_TO_FIXED_LINES  M1_V_MINUTES_TO_FIXED_LINES  \
0                         15                    28.216667   
1                         10                    44.383333   
2                          4                     6.383333   
3                          0                     0.000000   
4                          0                     0.000000   

   M1_V_REVENUE_TO_FIXED_LINES  M1_V_CALLS_TO_COMPETITION  \
0                          0.0                         13   
1                          0.0                        103   
2                          0.0                          4   
3                          0.0                          0   
4                          0.0                         19   

   M1_V_MINUTES_TO_COMPETITION  M1_V_REVENUE_TO_COMPETITION  \
0                    28.150000                          0.0   
1                   324.616667                          0.0   
2                     3.933333                          0.0   
3                     0.000000                          0.0   
4                    13.983333                          0.0   

   M1_V_CALLS_TO_INTERNATIONAL  M1_V_MINUTES_TO_INTERNATIONAL  \
0                            0                            0.0   
1                            0                            0.0   
2                            0                            0.0   
3                            0                            0.0   
4                            0                            0.0   

   M1_V_REVENUE_TO_INTERNATIONAL  M1_GPRS_SESSION  M1_GPRS_REVENUE  \
0                            0.0              181              0.0   
1                            0.0                0              0.0   
2                            0.0              241              0.0   
3                            0.0              146              0.0   
4                            0.0              736              0.0   

   M1_GPRS_VOLUME  M1_RECHARGES_NUMBER  M1_RECHARGES_VALUE  M1_OUT_DAYS  \
0     1345.479857                    1               10.91           22   
1        0.000000                    1               10.91           30   
2     1942.154999                    0                0.00           12   
3     3448.914274                    0                0.00            4   
4    11971.724609                    1               13.64           14   

   M1_INC_DAYS  M1_BUNDLE_REVENUE  M2_TTL_OUT_CALLS  M2_TTL_OUT_MINUTES  \
0           14               10.0             105.0           37.166667   
1           25               10.0             120.0          413.066667   
2           28                0.0              17.0            5.300000   
3           25                7.1              26.0           11.266667   
4           13               12.1              38.0           24.183333   

   M2_TTL_OUT_REVENUE  M2_V_CALLS_TO_FIXED_LINES  M2_V_MINUTES_TO_FIXED_LINES  \
0              0.0000                        8.0                    13.916667   
1              4.8600                       25.0                   128.666667   
2              0.0000                        2.0                     0.450000   
3              0.0000                        0.0                     0.000000   
4              5.1019                        0.0                     0.000000   

   M2_V_REVENUE_TO_FIXED_LINES  M2_V_CALLS_TO_COMPETITION  \
0                          0.0                        7.0   
1                          0.0                       84.0   
2                          0.0                        4.0  

In [5]:
out_dir = 'C:/Users/zagkoui/OneDrive - Vodafone Group/Documents/HIGHER_BUNDLES/models/'

In [6]:
previous_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 907206 entries, 0 to 907205
Columns: 265 entries, MSISDN to HIGHER_BUNDLE
dtypes: float64(244), int64(10), object(11)
memory usage: 1.8+ GB


In [7]:
previous_dataset["HIGHER_BUNDLE"].value_counts()

0.0    868096
1.0     39110
Name: HIGHER_BUNDLE, dtype: int64

# FUNCTIONS

In [8]:
def downsampling(dataset, n_majority):
    dataset_major = dataset[(dataset['HIGHER_BUNDLE'] == 0)]
    dataset_minor = dataset[(dataset['HIGHER_BUNDLE'] == 1)]
    major = dataset_major.sample(n=n_majority, random_state=10) #downsampling
    df_sampled = pd.concat([major, dataset_minor])
    df_shuffled = df_sampled.sample(frac=1)
    
    return df_shuffled

In [9]:
def split_x_y(df):
    X = df.drop(["MSISDN","HIGHER_BUNDLE", "INSERTED", "CONNECTION_DAY", "Periferiaki_enotita", "Name", "POST_CODE"], axis=1)
    y = df["HIGHER_BUNDLE"].values
    
    return X,y

In [10]:
def encoding_data(X, y):
    le = LabelEncoder()
    objects = X.select_dtypes(include=['object'])
    object_names = list(objects.columns.values)
    
    # Encoding all the categorical columns
    for object_name in object_names:
        if (X[object_name].nunique() > 2):
            enc_pc = pd.get_dummies(X[object_name], drop_first = True)
            X = X.drop(object_name, axis = 1)
            X = pd.concat([X,enc_pc], axis = 1)
        elif (X[object_name].nunique() <= 2):
            le.fit(X[object_name].astype(str))
            X[object_name] = le.transform(X[object_name].astype(str))


    y = le.fit_transform(y)
    
    return X,y

In [1]:
def estimate_proportion(y):
    count_train_0= (y == 0).sum()
    count_train_1= (y == 1).sum()
    
    proportion = float(float(count_train_0) / float(count_train_1))
    
    return proportion

In [12]:
def split_train_test(X,y):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 1)
    
    return X_train, X_test, y_train, y_test

In [13]:
def evaluation(X_test, y_test, classifier):
    y_pred = classifier.predict(X_test)
    cm = confusion_matrix(y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)
    
    target_names = ['No higher bundle', 'Higher Bundle']
    evaluation_report = classification_report(y_test, y_pred, target_names=target_names)
    
    return cm, accuracy, evaluation_report

In [ ]:
def feature_importance(X_test, classifier):
    explainer = shap.TreeExplainer(classifier)
    shap_values = explainer.shap_values(X_test)
    shap.summary_plot(shap_values, X_test, feature_names, plot_type="bar")
    
    shap.summary_plot(shap_values, X_test, feature_names)

# PREPARE DATASET

In [14]:
# Downsampling
previous_sampled_dataset = downsampling(previous_dataset, n_majority= 100000)  # change this number
# Define X and y
X_previous, y_previous = split_x_y(previous_sampled_dataset)
# Encoding
X_previous, y_previous = encoding_data(X_previous,y_previous)
# Save feature name
feature_names= np.array(X_previous.columns)

In [15]:
previous_proportion = estimate_proportion(y_previous)
print(previous_proportion)

2.0


In [16]:
X_previous_new = X_previous.rename(columns = lambda x:re.sub('[^A-Za-z0-9_]+', '', x))

# TRAINING

In [17]:
lgbm = lgb.LGBMClassifier(boosting_type = 'gbdt',
                                    importance_type = 'gain',
                                    scale_pos_weight= previous_proportion,
                                    n_estimators = 1000,
                                    learning_rate=0.01, metric='auc', silent=True, n_jobs=-1, random_state=10) 

In [23]:
# lgbm = lgb.LGBMClassifier(boosting_type = 'gbdt',
#                                     importance_type = 'gain',
#                                     scale_pos_weight= 12,
#                                     n_estimators = 500,
#                                     learning_rate=0.1, metric='auc', silent=True, n_jobs=-1, random_state=10) 

In [18]:
lgbm.fit(X_previous_new, y_previous)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.01, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=1000, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=2.0, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

In [25]:
#joblib.dump(lgbm, os.path.join(out_dir, 'model.pkl'))

['C:/Users/zagkoui/OneDrive - Vodafone Group/Documents/HIGHER_BUNDLES/models/model.pkl']

# EVALUATION

In [19]:
next_dataset = pd.read_csv('C:/Users/zagkoui/OneDrive - Vodafone Group/Documents/HIGHER_BUNDLES/final_data/test/final_customer_db.csv', index_col=0)

In [20]:
# Define X and y
X_next, y_next = split_x_y(next_dataset)
# Encoding
X_next, y_next = encoding_data(X_next,y_next)
# Save feature name
feature_names = np.array(X_next.columns)

In [21]:
cm, acc, class_report = evaluation(X_next, y_next, lgbm)
print(cm)
print(acc)
print(class_report)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[673284 202319]
 [  8651  23578]]
0.7676111879731051
                  precision    recall  f1-score   support

No higher bundle       0.99      0.77      0.86    875603
   Higher Bundle       0.10      0.73      0.18     32229

     avg / total       0.96      0.77      0.84    907832



# Feature importance

In [ ]:
feature_importance(X_next, loaded_model)

In [ ]:
pred_y_propab = loaded_model.predict_proba(X_next)
pred_y_propab[:,1]
condition = pred_y_propab[:,1] >= 0.5
len(pred_y_propab[:,1][condition])

# TUNING

In [23]:
for booster in ['gbdt', 'dart']:
    for scale in [2, 4]:
    #for scale in [feb_proportion/2, feb_proportion]:
        for est in [100, 500, 1000]:
            for lr in [0.01, 0.1]:
                print (booster, scale, est, lr)
                # ----------------TRAINING-------------------
                lgbm = lgb.LGBMClassifier(boosting_type = booster,
                                    importance_type = 'gain',
                                    scale_pos_weight= scale,
                                    n_estimators = est,
                                    learning_rate=lr, metric='auc', silent=True, n_jobs=-1, random_state=10) 

                lgbm.fit(X_previous_new, y_previous)
                # ----------------TESTING-------------------
                cm, acc, class_report = evaluation(X_next, y_next, lgbm)
                print(cm)
                print(acc)
                print(class_report)

                # -----------------EVALUATION-------------------
                pred_y_propab = lgbm.predict_proba(X_next)
                pred_y_propab[:,1]
                condition = pred_y_propab[:,1] >= 0.5
                len(pred_y_propab[:,1][condition])

('gbdt', 2, 100, 0.01)


LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.01, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=100, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=2, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[816749  58854]
 [ 23284   8945]]
0.9095229073220595
                  precision    recall  f1-score   support

No higher bundle       0.97      0.93      0.95    875603
   Higher Bundle       0.13      0.28      0.18     32229

     avg / total       0.94      0.91      0.92    907832



array([0.10791508, 0.43173956, 0.14413622, ..., 0.26971628, 0.43461874,
       0.24286671])

67799

('gbdt', 2, 100, 0.1)


LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.1, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=100, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=2, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[671971 203632]
 [  8666  23563]]
0.7661483622520466
                  precision    recall  f1-score   support

No higher bundle       0.99      0.77      0.86    875603
   Higher Bundle       0.10      0.73      0.18     32229

     avg / total       0.96      0.77      0.84    907832



array([0.00174663, 0.45312494, 0.00623511, ..., 0.04478675, 0.45941858,
       0.1925389 ])

227195

('gbdt', 2, 500, 0.01)


LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.01, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=500, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=2, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[679232 196371]
 [  9393  22836]]
0.7733457291657487
                  precision    recall  f1-score   support

No higher bundle       0.99      0.78      0.87    875603
   Higher Bundle       0.10      0.71      0.18     32229

     avg / total       0.96      0.77      0.84    907832



array([0.00444493, 0.49838442, 0.0178674 , ..., 0.13184081, 0.50571852,
       0.21754727])

219207

('gbdt', 2, 500, 0.1)


LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.1, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=500, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=2, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[685659 189944]
 [  9800  22429]]
0.7799769120277761
                  precision    recall  f1-score   support

No higher bundle       0.99      0.78      0.87    875603
   Higher Bundle       0.11      0.70      0.18     32229

     avg / total       0.95      0.78      0.85    907832



array([0.00060896, 0.37972961, 0.00174184, ..., 0.00763554, 0.30200842,
       0.20868613])

212373

('gbdt', 2, 1000, 0.01)


LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.01, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=1000, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=2, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[673284 202319]
 [  8651  23578]]
0.7676111879731051
                  precision    recall  f1-score   support

No higher bundle       0.99      0.77      0.86    875603
   Higher Bundle       0.10      0.73      0.18     32229

     avg / total       0.96      0.77      0.84    907832



array([0.00155534, 0.49404693, 0.00725958, ..., 0.07493424, 0.48386451,
       0.20904546])

225897

('gbdt', 2, 1000, 0.1)


LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.1, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=1000, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=2, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[700677 174926]
 [ 11149  21080]]
0.7950336626159906
                  precision    recall  f1-score   support

No higher bundle       0.98      0.80      0.88    875603
   Higher Bundle       0.11      0.65      0.18     32229

     avg / total       0.95      0.80      0.86    907832



array([2.73281189e-04, 3.43916969e-01, 8.03946002e-04, ...,
       5.83854860e-03, 3.05433924e-01, 1.47237421e-01])

196006

('gbdt', 4, 100, 0.01)


LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.01, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=100, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=4, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[643247 232356]
 [  8850  23379]]
0.734305466209607
                  precision    recall  f1-score   support

No higher bundle       0.99      0.73      0.84    875603
   Higher Bundle       0.09      0.73      0.16     32229

     avg / total       0.95      0.73      0.82    907832



array([0.1072472 , 0.56002161, 0.16462712, ..., 0.41771418, 0.44087901,
       0.28711574])

255735

('gbdt', 4, 100, 0.1)


LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.1, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=100, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=4, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[561515 314088]
 [  3936  28293]]
0.6496884886190396
                  precision    recall  f1-score   support

No higher bundle       0.99      0.64      0.78    875603
   Higher Bundle       0.08      0.88      0.15     32229

     avg / total       0.96      0.65      0.76    907832



array([0.0030379 , 0.69643947, 0.00678626, ..., 0.1093575 , 0.60654128,
       0.30572008])

342381

('gbdt', 4, 500, 0.01)


LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.01, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=500, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=4, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[546025 329578]
 [  3710  28519]]
0.6328748050300056
                  precision    recall  f1-score   support

No higher bundle       0.99      0.62      0.77    875603
   Higher Bundle       0.08      0.88      0.15     32229

     avg / total       0.96      0.63      0.74    907832



array([0.00655774, 0.68837601, 0.02177025, ..., 0.23183687, 0.60180747,
       0.33326678])

358097

('gbdt', 4, 500, 0.1)


LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.1, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=500, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=4, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[599743 275860]
 [  5774  26455]]
0.6897729976471417
                  precision    recall  f1-score   support

No higher bundle       0.99      0.68      0.81    875603
   Higher Bundle       0.09      0.82      0.16     32229

     avg / total       0.96      0.69      0.79    907832



array([5.75953898e-04, 7.84621722e-01, 1.59790054e-03, ...,
       1.99409936e-02, 4.94586837e-01, 3.20088376e-01])

302315

('gbdt', 4, 1000, 0.01)


LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.01, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=1000, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=4, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[554011 321592]
 [  3669  28560]]
0.6417167493545061
                  precision    recall  f1-score   support

No higher bundle       0.99      0.63      0.77    875603
   Higher Bundle       0.08      0.89      0.15     32229

     avg / total       0.96      0.64      0.75    907832



array([0.002853  , 0.65687402, 0.00990353, ..., 0.12412344, 0.5470062 ,
       0.3205644 ])

350152

('gbdt', 4, 1000, 0.1)


LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.1, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=1000, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=4, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[645003 230600]
 [  8242  23987]]
0.736909472237154
                  precision    recall  f1-score   support

No higher bundle       0.99      0.74      0.84    875603
   Higher Bundle       0.09      0.74      0.17     32229

     avg / total       0.96      0.74      0.82    907832



array([4.06383815e-04, 7.66512219e-01, 1.06790530e-03, ...,
       1.62980816e-02, 4.96768490e-01, 1.99297135e-01])

254587

('gbdt', 8, 100, 0.01)


LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.01, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=100, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=8, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[483041 392562]
 [  2910  29319]]
0.5643775500312833
                  precision    recall  f1-score   support

No higher bundle       0.99      0.55      0.71    875603
   Higher Bundle       0.07      0.91      0.13     32229

     avg / total       0.96      0.56      0.69    907832



array([0.10872291, 0.62794683, 0.1217807 , ..., 0.56578964, 0.54538089,
       0.40866276])

421881

('gbdt', 8, 100, 0.1)


LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.1, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=100, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=8, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[453558 422045]
 [  1582  30647]]
0.5333641026092933
                  precision    recall  f1-score   support

No higher bundle       1.00      0.52      0.68    875603
   Higher Bundle       0.07      0.95      0.13     32229

     avg / total       0.96      0.53      0.66    907832



array([0.0044267 , 0.73943169, 0.0042667 , ..., 0.27977729, 0.69441195,
       0.48201063])

452692

('gbdt', 8, 500, 0.01)


LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.01, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=500, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=8, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[434969 440634]
 [  1363  30866]]
0.5131290811515787
                  precision    recall  f1-score   support

No higher bundle       1.00      0.50      0.66    875603
   Higher Bundle       0.07      0.96      0.12     32229

     avg / total       0.96      0.51      0.64    907832



array([0.00926611, 0.79635921, 0.01314553, ..., 0.37641101, 0.76401046,
       0.54279558])

471500

('gbdt', 8, 500, 0.1)


LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.1, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=500, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=8, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[523889 351714]
 [  3569  28660]]
0.6086467540249738
                  precision    recall  f1-score   support

No higher bundle       0.99      0.60      0.75    875603
   Higher Bundle       0.08      0.89      0.14     32229

     avg / total       0.96      0.61      0.73    907832



array([0.00157603, 0.83024085, 0.00152091, ..., 0.07980691, 0.18917014,
       0.47785918])

380374

('gbdt', 8, 1000, 0.01)


LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.01, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=1000, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=8, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[450036 425567]
 [  1504  30725]]
0.529570449157994
                  precision    recall  f1-score   support

No higher bundle       1.00      0.51      0.68    875603
   Higher Bundle       0.07      0.95      0.13     32229

     avg / total       0.96      0.53      0.66    907832



array([0.0038189 , 0.79475429, 0.00620976, ..., 0.27618465, 0.72751409,
       0.51459958])

456292

('gbdt', 8, 1000, 0.1)


LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.1, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=1000, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=8, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[581665 293938]
 [  5873  26356]]
0.6697505705901532
                  precision    recall  f1-score   support

No higher bundle       0.99      0.66      0.80    875603
   Higher Bundle       0.08      0.82      0.15     32229

     avg / total       0.96      0.67      0.77    907832



array([0.00124761, 0.61079892, 0.0006337 , ..., 0.07575022, 0.07701748,
       0.41450594])

320294

('dart', 2, 100, 0.01)


LGBMClassifier(boosting_type='dart', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.01, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=100, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=2, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[853184  22419]
 [ 28327   3902]]
0.9441019924391297
                  precision    recall  f1-score   support

No higher bundle       0.97      0.97      0.97    875603
   Higher Bundle       0.15      0.12      0.13     32229

     avg / total       0.94      0.94      0.94    907832



array([0.28915408, 0.44693255, 0.31279592, ..., 0.34387749, 0.4740294 ,
       0.36267022])

26321

('dart', 2, 100, 0.1)


LGBMClassifier(boosting_type='dart', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.1, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=100, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=2, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[687320 188283]
 [ 10210  22019]]
0.7813549202936226
                  precision    recall  f1-score   support

No higher bundle       0.99      0.78      0.87    875603
   Higher Bundle       0.10      0.68      0.18     32229

     avg / total       0.95      0.78      0.85    907832



array([0.01659537, 0.52374433, 0.04187423, ..., 0.20685461, 0.47985494,
       0.3057992 ])

210302

('dart', 2, 500, 0.01)


LGBMClassifier(boosting_type='dart', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.01, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=500, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=2, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[707186 168417]
 [ 12760  19469]]
0.8004289339877863
                  precision    recall  f1-score   support

No higher bundle       0.98      0.81      0.89    875603
   Higher Bundle       0.10      0.60      0.18     32229

     avg / total       0.95      0.80      0.86    907832



array([0.15350685, 0.51630767, 0.19325917, ..., 0.31101624, 0.50931324,
       0.32738657])

187886

('dart', 2, 500, 0.1)


LGBMClassifier(boosting_type='dart', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.1, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=500, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=2, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[679224 196379]
 [  8716  23513]]
0.7740826496532398
                  precision    recall  f1-score   support

No higher bundle       0.99      0.78      0.87    875603
   Higher Bundle       0.11      0.73      0.19     32229

     avg / total       0.96      0.77      0.84    907832



array([0.00116508, 0.52160585, 0.00359444, ..., 0.08156262, 0.48148684,
       0.28258161])

219892

('dart', 2, 1000, 0.01)


LGBMClassifier(boosting_type='dart', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.01, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=1000, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=2, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[689630 185973]
 [ 10916  21313]]
0.7831217670229734
                  precision    recall  f1-score   support

No higher bundle       0.98      0.79      0.88    875603
   Higher Bundle       0.10      0.66      0.18     32229

     avg / total       0.95      0.78      0.85    907832



array([0.05401643, 0.50656942, 0.09391616, ..., 0.25730011, 0.50474034,
       0.29221461])

207286

('dart', 2, 1000, 0.1)


LGBMClassifier(boosting_type='dart', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.1, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=1000, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=2, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[684439 191164]
 [  9057  23172]]
0.7794514844156187
                  precision    recall  f1-score   support

No higher bundle       0.99      0.78      0.87    875603
   Higher Bundle       0.11      0.72      0.19     32229

     avg / total       0.96      0.78      0.85    907832



array([0.00063764, 0.56747393, 0.0010225 , ..., 0.09590477, 0.36176574,
       0.23286721])

214336

('dart', 4, 100, 0.01)


LGBMClassifier(boosting_type='dart', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.01, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=100, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=4, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[702810 172793]
 [ 13301  18928]]
0.7950127336335358
                  precision    recall  f1-score   support

No higher bundle       0.98      0.80      0.88    875603
   Higher Bundle       0.10      0.59      0.17     32229

     avg / total       0.95      0.80      0.86    907832



array([0.28853895, 0.50993001, 0.32942654, ..., 0.43610837, 0.46330463,
       0.36625705])

191721

('dart', 4, 100, 0.1)


LGBMClassifier(boosting_type='dart', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.1, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=100, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=4, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[541611 333992]
 [  3689  28540]]
0.6280358039813534
                  precision    recall  f1-score   support

No higher bundle       0.99      0.62      0.76    875603
   Higher Bundle       0.08      0.89      0.14     32229

     avg / total       0.96      0.63      0.74    907832



array([0.01866966, 0.63390093, 0.04457083, ..., 0.30422499, 0.61685825,
       0.39054809])

362532

('dart', 4, 500, 0.01)


LGBMClassifier(boosting_type='dart', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.01, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=500, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=4, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[534730 340873]
 [  4033  28196]]
0.6200772830215282
                  precision    recall  f1-score   support

No higher bundle       0.99      0.61      0.76    875603
   Higher Bundle       0.08      0.87      0.14     32229

     avg / total       0.96      0.62      0.73    907832



array([0.15440587, 0.62194863, 0.20959367, ..., 0.40872565, 0.56770913,
       0.36746205])

369069

('dart', 4, 500, 0.1)


LGBMClassifier(boosting_type='dart', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.1, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=500, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=4, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[550398 325205]
 [  3461  28768]]
0.6379660553935089
                  precision    recall  f1-score   support

No higher bundle       0.99      0.63      0.77    875603
   Higher Bundle       0.08      0.89      0.15     32229

     avg / total       0.96      0.64      0.75    907832



array([0.00163744, 0.65828397, 0.00386688, ..., 0.16879158, 0.57964575,
       0.44045549])

353973

('dart', 4, 1000, 0.01)


LGBMClassifier(boosting_type='dart', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.01, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=1000, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=4, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[535082 340521]
 [  3843  28386]]
0.6206743097841891
                  precision    recall  f1-score   support

No higher bundle       0.99      0.61      0.76    875603
   Higher Bundle       0.08      0.88      0.14     32229

     avg / total       0.96      0.62      0.73    907832



array([0.05543303, 0.65348832, 0.09662099, ..., 0.35609612, 0.5885256 ,
       0.40952428])

368907

('dart', 4, 1000, 0.1)


LGBMClassifier(boosting_type='dart', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.1, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=1000, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=4, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[569870 305733]
 [  4144  28085]]
0.6586626159906238
                  precision    recall  f1-score   support

No higher bundle       0.99      0.65      0.79    875603
   Higher Bundle       0.08      0.87      0.15     32229

     avg / total       0.96      0.66      0.76    907832



array([6.78970780e-04, 7.48580994e-01, 1.24451326e-03, ...,
       1.39532154e-01, 4.54855580e-01, 4.75547307e-01])

333818

('dart', 8, 100, 0.01)


LGBMClassifier(boosting_type='dart', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.01, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=100, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=8, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[515772 359831]
 [  3950  28279]]
0.5992859912406701
                  precision    recall  f1-score   support

No higher bundle       0.99      0.59      0.74    875603
   Higher Bundle       0.07      0.88      0.13     32229

     avg / total       0.96      0.60      0.72    907832



array([0.29057168, 0.53936596, 0.32756109, ..., 0.51405133, 0.49752713,
       0.42190576])

388110

('dart', 8, 100, 0.1)


LGBMClassifier(boosting_type='dart', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.1, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=100, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=8, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[429260 446343]
 [  1325  30904]]
0.5068823306514861
                  precision    recall  f1-score   support

No higher bundle       1.00      0.49      0.66    875603
   Higher Bundle       0.06      0.96      0.12     32229

     avg / total       0.96      0.51      0.64    907832



array([0.02318663, 0.77899066, 0.03699479, ..., 0.54531483, 0.73421214,
       0.54871073])

477247

('dart', 8, 500, 0.01)


LGBMClassifier(boosting_type='dart', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.01, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=500, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=8, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[412653 462950]
 [  1342  30887]]
0.48857057252883795
                  precision    recall  f1-score   support

No higher bundle       1.00      0.47      0.64    875603
   Higher Bundle       0.06      0.96      0.12     32229

     avg / total       0.96      0.49      0.62    907832



array([0.15572474, 0.71028502, 0.19099524, ..., 0.61369114, 0.61930486,
       0.46812473])

493837

('dart', 8, 500, 0.1)


LGBMClassifier(boosting_type='dart', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.1, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=500, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=8, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[449476 426127]
 [  1391  30838]]
0.5290780673076075
                  precision    recall  f1-score   support

No higher bundle       1.00      0.51      0.68    875603
   Higher Bundle       0.07      0.96      0.13     32229

     avg / total       0.96      0.53      0.66    907832



array([0.00160683, 0.8217521 , 0.00324036, ..., 0.34479543, 0.67459651,
       0.57147529])

456965

('dart', 8, 1000, 0.01)


LGBMClassifier(boosting_type='dart', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.01, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=1000, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=8, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[412857 462746]
 [  1216  31013]]
0.48893407590831783
                  precision    recall  f1-score   support

No higher bundle       1.00      0.47      0.64    875603
   Higher Bundle       0.06      0.96      0.12     32229

     avg / total       0.96      0.49      0.62    907832



array([0.05918418, 0.76506907, 0.09345485, ..., 0.4868084 , 0.69200893,
       0.55009246])

493759

('dart', 8, 1000, 0.1)


LGBMClassifier(boosting_type='dart', class_weight=None, colsample_bytree=1.0,
        importance_type='gain', learning_rate=0.1, max_depth=-1,
        metric='auc', min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=1000, n_jobs=-1, num_leaves=31,
        objective=None, random_state=10, reg_alpha=0.0, reg_lambda=0.0,
        scale_pos_weight=8, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=0)

C:\Users\zagkoui\AppData\Local\conda\conda\envs\irida\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[486624 388979]
 [  2133  30096]]
0.5691802007419875
                  precision    recall  f1-score   support

No higher bundle       1.00      0.56      0.71    875603
   Higher Bundle       0.07      0.93      0.13     32229

     avg / total       0.96      0.57      0.69    907832



array([0.00101694, 0.73737867, 0.00082597, ..., 0.37711577, 0.69291584,
       0.60177926])

419075